name: Réentrainement du modèle

on:
  push:
    branches: ['master']
  schedule:
    - cron: "15 21 * * TUE"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: isa-2
  user: steevedo
  TZ: "Europe/Paris"
  
jobs:
  test-date:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Test schedule
        run: echo " $(date +'%Y-%m-%d')"
  