name: Réentrainement du modèle

on:
  schedule:
    - cron: "*/15 * * * *"
env:
  LOCAL_TIME: "02:16"

jobs:
  test-date:
    runs-on: ubuntu-latest

    steps:
      - name: Test schedule
        run:  |
          now=$(date +%s)
          local_time=$(date -d "$LOCAL_TIME" +%s)

          if [[ $now -gt $local_time && $now -lt "$((local_time + 3600))" ]]; then
              echo "🌞 Passed daylight savings time check!"
          else    
              echo "⏱ Waiting until $LOCAL_TIME."
          fi
  